import { notFound } from "next/navigation";
import Image from "next/image";
import { PrintButton } from "@/components/print-button";
import { requireOrganiserBySlug } from "@/server/auth/guards";
import { getDb } from "@/server/db";
import { buildPrintPack, PRINT_KINDS, type PrintKind } from "@/server/exports/print-pack";
import { loadGraph } from "@/server/services/graph";
import { PrintPage } from "@/ui/print-page";

export default async function PrintRoute({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string; kind: string }>;
  searchParams: Promise<{ division?: string }>;
}) {
  const { slug, kind } = await params;
  if (!PRINT_KINDS.includes(kind as PrintKind)) notFound();
  const access = await requireOrganiserBySlug(slug);
  if (kind === "judges" && access.membership.role !== "owner") notFound();
  const { division } = await searchParams;
  const pack = await buildPrintPack(
    await loadGraph(await getDb(), access.tournament.id),
    kind as PrintKind,
    division,
  );
  return (
    <div>
      <div data-print="hide" className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <h1 id="page-title" tabIndex={-1} className="text-3xl font-semibold">
          {pack.title}
        </h1>
        <PrintButton />
      </div>
      {!pack.sections.length && <p>No records to print yet. Complete the draw first.</p>}
      {pack.sections.map((section, index) => (
        <PrintPage
          key={index}
          title={pack.title}
          tournamentName={pack.tournament}
          generatedAt={new Date(pack.generatedAt).toLocaleString("en-GB", {
            timeZone: "America/Cayman",
          })}
          orientation={kind === "scoresheets" ? "landscape" : "portrait"}
          status={
            kind === "results"
              ? section.subtitle === "Published"
                ? "published"
                : "provisional"
              : "draft"
          }
        >
          {pack.practice && <p className="mb-4 font-semibold">DEMO / PRACTICE</p>}
          <h2 className="mb-2 text-3xl font-semibold">{section.title}</h2>
          {section.subtitle && <p className="mb-6">{section.subtitle}</p>}
          {/* A local data URL generated by qrcode, never a remote image. */}
          {section.qr && (
            <Image
              unoptimized
              src={section.qr}
              width={180}
              height={180}
              alt={`Sign-in QR for ${section.title}`}
              className="mb-6"
            />
          )}
          <div
            className="overflow-x-auto"
            tabIndex={0}
            role="region"
            aria-label={`${section.title} table`}
          >
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr>
                  {section.columns.map((column, n) => (
                    <th key={n} className="border-b px-3 py-3 text-left">
                      {column}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {section.rows.map((row, n) => (
                  <tr key={n}>
                    {row.map((value, k) => (
                      <td key={k} className="whitespace-pre-wrap border-b px-3 py-4 align-top">
                        {value}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-6 space-y-2">
            {section.notes.map((note, n) => (
              <p key={n} className="text-sm">
                {note}
              </p>
            ))}
          </div>
        </PrintPage>
      ))}
    </div>
  );
}
